version: "3.9"
services:

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
      MONGO_INITDB_DATABASE: employees
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  fastapi:
    build: .
    restart: unless-stopped
    env_file: ./src/.env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - mongodb
    networks:
      - backend

  nginx:
    image: 'nginx:1.23.3'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    env_file: ./src/.env
    depends_on:
      - fastapi
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  mongodbdata:
